services:
  server:
    build:
      context: .
      args:
        ENV: ${ENV:-dev}
    image: netflix:${ENV:-dev}
    environment:
      - ENV=${ENV:-development}
    ports:
      - "3000:3000"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8080:8080"
    depends_on:
      - server
